OOOVote/OOOVote/Pages/Organizations/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OOOVote.Data;
using OOOVote.Data.Entities;

namespace OOOVote.Pages.Organizations
{
    public class CreateModel : PageModel
    {
        private readonly OOOVote.Data.ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public CreateModel(OOOVote.Data.ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Organization Organization { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (!Guid.TryParse(_userManager.GetUserId(User), out Guid id))
            {
                return Page();
            }

            _context.Organizations.Add(Organization);

            await _context.SaveChangesAsync();

            Organization.Users.Add(new OrganizationUser
            {
                UserId = id,
                OrganizationId = Organization.Id,
                OrganizationRole = Organization.RuleType == RuleType.Single ? OrganizationRole.CEO : OrganizationRole.TopManager
            });

            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

OOOVote/OOOVote/Pages/Organizations/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OOOVote.Data;
using OOOVote.Data.Entities;

namespace OOOVote.Pages.Organizations
{
    public class DeleteModel : PageModel
    {
        private readonly OOOVote.Data.ApplicationDbContext _context;

        public DeleteModel(OOOVote.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Organization Organization { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Organization = await _context.Organizations.FirstOrDefaultAsync(m => m.Id == id);

            if (Organization == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Organization = await _context.Organizations.FindAsync(id);

            if (Organization != null)
            {
                _context.Organizations.Remove(Organization);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

OOOVote/OOOVote/Pages/Organizations/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OOOVote.Data;
using OOOVote.Data.Entities;

namespace OOOVote.Pages.Organizations
{
    public class OrganizationUserViewModel
    {
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public OrganizationRole Role { get; set; }
    }
    public class DetailsModel : PageModel
    {
        private readonly OOOVote.Data.ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public DetailsModel(OOOVote.Data.ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public Organization Organization { get; set; }
        public List<OrganizationUserViewModel> Users { get; set; } = new List<OrganizationUserViewModel>();
        public bool CanEditOrganization { get; set; } = false;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!Guid.TryParse(_userManager.GetUserId(User), out Guid userId))
            {
                return NotFound();
            }

            Organization = await _context.Organizations
                .Include(u => u.Users)
                    .ThenInclude(ou => ou.User)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (Organization == null)
            {
                return NotFound();
            }

            Users = Organization.Users
                .Select(ou => new OrganizationUserViewModel
                {
                    Id = ou.UserId,
                    FirstName = ou.User.FirstName,
                    LastName = ou.User.LastName,
                    Role = ou.OrganizationRole
                })
                .ToList();

            var currentRole = Organization.Users.FirstOrDefault(ou => ou.UserId == userId)?.OrganizationRole;

            if(currentRole == OrganizationRole.CEO || currentRole==OrganizationRole.TopManager)
            {
                CanEditOrganization = true;
            }
            else
            {
                CanEditOrganization = false;
            }

            return Page();
        }
    }
}

OOOVote/OOOVote/Pages/Organizations/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OOOVote.Data;
using OOOVote.Data.Entities;

namespace OOOVote.Pages.Organizations
{
    public class EditModel : PageModel
    {
        private readonly OOOVote.Data.ApplicationDbContext _context;

        public EditModel(OOOVote.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Organization Organization { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Organization = await _context.Organizations.FirstOrDefaultAsync(m => m.Id == id);

            if (Organization == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Organization).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrganizationExists(Organization.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool OrganizationExists(Guid id)
        {
            return _context.Organizations.Any(e => e.Id == id);
        }
    }
}

OOOVote/OOOVote/Pages/Votings/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OOOVote.Data;
using OOOVote.Data.Entities;
using PdfRpt.Core.Contracts;
using PdfRpt.FluentInterface;

namespace OOOVote.Pages
{
    public class VotingResult
    {
        public int AgreeCount { get; set; }
        public int DisagreeCount { get; set; }
        public int NotVotedCount { get; set; }

        public int AllVotedCount { get; set; }

    }

    public class VotingPdfResult
    {
        public string Question { get; set; }
        public int AgreeCount { get; set; }
        public int DisagreeCount { get; set; }
        public int NotVotedCount { get; set; }

        public int AllVotedCount { get; set; }

        public string Resolution { get; set; }

    }

    public class DetailsModel : PageModel
    {
        private readonly OOOVote.Data.ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public DetailsModel(OOOVote.Data.ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public Voting Voting { get; set; }

        public Dictionary<Guid, VoteDecision> UserVotes { get; set; } = new Dictionary<Guid, VoteDecision>();

        public Dictionary<string, VotingResult> VotingResults { get; set; } = new Dictionary<string, VotingResult>();

        [BindProperty]
        public bool ShowResults { get; set; } = false;

        [BindProperty]
        public bool IsVotingEnded { get; set; } = false;

        [BindProperty]
        public int UserCount { get; set; } = 0;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!Guid.TryParse(_userManager.GetUserId(User), out Guid userId))
            {
                return BadRequest();
            }

            Voting = await _context.Votings
                .Include(v => v.VotingMessages)
                    .ThenInclude(vm => vm.User)
                .Include(v => v.VotingOptions)
                    .ThenInclude(v => v.Decisions)
                .Include(v => v.Organization)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (Voting == null)
            {
                return NotFound();
            }

            UserCount = (await _context.Organizations
                .Include(o => o.Users)
                .FirstOrDefaultAsync(o => o.Id == Voting.OrganizationId))
                ?.Users?.Count ?? 0;

            UserVotes = Voting.VotingOptions.ToDictionary(v => v.Id, v => VoteDecision.NotVoted);

            var userDecisions = Voting.VotingOptions
                .SelectMany(v => v.Decisions)
                .Where(d => d.UserId == userId)
                .ToList();

            bool hasUserDecisions = userDecisions.Count >= Voting.VotingOptions.Count;

            ShowResults = hasUserDecisions || Voting.EndDate < DateTime.Now;

            IsVotingEnded = Voting.EndDate < DateTime.Now || Voting.VotingOptions
                .Select(v => v.Decisions)
                .All(d => d.Count >= UserCount * 0.51);

            if (ShowResults)
            {
                VotingResults = Voting.VotingOptions
                    .Select(vo => new { Title = vo.Title, Decisions = vo.Decisions })
                    .ToDictionary(x => x.Title, vx =>
                      {
                          return new VotingResult
                          {
                              AgreeCount = vx.Decisions.Count(x => x.Decision == VoteDecision.Agree),
                              DisagreeCount = vx.Decisions.Count(x => x.Decision == VoteDecision.Disagree),
                              NotVotedCount = vx.Decisions.Count(x => x.Decision == VoteDecision.NotVoted),
                              AllVotedCount = vx.Decisions.Count()
                          };
                      });
            }

            return Page();
        }

        public async Task<IActionResult> OnPostDownloadFile(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!Guid.TryParse(_userManager.GetUserId(User), out Guid userId))
            {
                return BadRequest();
            }

            Voting = await _context.Votings
                .Include(v => v.VotingMessages)
                    .ThenInclude(vm => vm.User)
                .Include(v => v.VotingOptions)
                    .ThenInclude(v => v.Decisions)
                .Include(v => v.Organization)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (Voting == null)
            {
                return NotFound();
            }

            UserCount = (await _context.Organizations
                .Include(o => o.Users)
                .FirstOrDefaultAsync(o => o.Id == Voting.OrganizationId))
                ?.Users?.Count ?? 0;

            UserVotes = Voting.VotingOptions.ToDictionary(v => v.Id, v => VoteDecision.NotVoted);

            var userDecisions = Voting.VotingOptions
                .SelectMany(v => v.Decisions)
                .Where(d => d.UserId == userId)
                .ToList();

            bool hasUserDecisions = userDecisions.Count >= Voting.VotingOptions.Count;

            ShowResults = hasUserDecisions || Voting.EndDate < DateTime.Now;

            IsVotingEnded = Voting.EndDate < DateTime.Now || Voting.VotingOptions
                .Select(v => v.Decisions)
                .All(d => d.Count >= UserCount * 0.51);

            if (ShowResults)
            {
                VotingResults = Voting.VotingOptions
                    .Select(vo => new { Title = vo.Title, Decisions = vo.Decisions })
                    .ToDictionary(x => x.Title, vx =>
                    {
                        return new VotingResult
                        {
                            AgreeCount = vx.Decisions.Count(x => x.Decision == VoteDecision.Agree),
                            DisagreeCount = vx.Decisions.Count(x => x.Decision == VoteDecision.Disagree),
                            NotVotedCount = vx.Decisions.Count(x => x.Decision == VoteDecision.NotVoted),
                            AllVotedCount = vx.Decisions.Count()
                        };
                    });
            }

            return new FileStreamResult(CreateIListPdfReport(Voting.Subject, VotingResults, UserCount).PdfStreamOutput, "application/pdf");
        }

        public async Task<IActionResult> OnPostAsync(Guid? id, Dictionary<Guid, VoteDecision> userVotes)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!Guid.TryParse(_userManager.GetUserId(User), out Guid userId))
            {
                return BadRequest();
            }

            var decisions = userVotes.Select(pair => new UserVotingDecision
            {
                Decision = pair.Value,
                VotingOptionId = pair.Key,
                UserId = userId
            });

            _context.VotingDecisions.AddRange(decisions);

            await _context.SaveChangesAsync();

            return await OnGetAsync(id);
        }

        private IPdfReportData CreateIListPdfReport(string subject, Dictionary<string, VotingResult> votingResults, int userCount)
        {
            var stream = new MemoryStream();

            return new PdfReport().DocumentPreferences(doc =>
            {
                doc.RunDirection(PdfRunDirection.LeftToRight);
                doc.Orientation(PageOrientation.Portrait);
                doc.PageSize(PdfPageSize.A4);
                doc.DocumentMetadata(new DocumentMetadata {
                    Author = "OOOVote",
                    Application = "OOOVote",
                    Subject = subject, Title = subject });
                doc.Compression(new CompressionSettings
                {
                    EnableCompression = true,
                    EnableFullCompression = true
                });
                doc.PrintingPreferences(new PrintingPreferences
                {
                    ShowPrintDialogAutomatically = true
                });
            })
            .DefaultFonts(fonts =>
            {
                fonts.Size(9);
                fonts.Color(System.Drawing.Color.Black);
            })
            .PagesFooter(footer =>
            {
                footer.DefaultFooter(DateTime.Now.ToString("MM/dd/yyyy"));
            })
            .PagesHeader(header =>
            {
                header.CacheHeader(cache: true); // It's a default setting to improve the performance.
                header.DefaultHeader(defaultHeader =>
                {
                    defaultHeader.RunDirection(PdfRunDirection.LeftToRight);
                    defaultHeader.Message($"Голосование: {subject}");
                });
            })
            .MainTableTemplate(template =>
            {
                template.BasicTemplate(BasicTemplate.SimpleTemplate);
            })
            .MainTablePreferences(table =>
            {
                table.ColumnsWidthsType(TableColumnWidthType.Relative);
                table.NumberOfDataRowsPerPage(5);
            })
            .MainTableDataSource(dataSource =>
            {
                dataSource.StronglyTypedList(votingResults.Select(v => new VotingPdfResult
                {
                    Question = v.Key,
                    AgreeCount = v.Value.AgreeCount,
                    DisagreeCount = v.Value.DisagreeCount,
                    NotVotedCount = v.Value.NotVotedCount,
                    Resolution =
                    (v.Value.AgreeCount * 1.0 / userCount * 100 > 51)

OOOVote/OOOVote/Pages/Votings/Create.cshtml
@page
@model OOOVote.Pages.CreateModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Новое голосование";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@ViewData["Title"]</h3>

<hr />
<form method="post">
    <div class="row">
        <div class="col-md-4">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Voting.Subject" class="control-label">Тема голосования</label>
                <input asp-for="Voting.Subject" class="form-control" />
                <span asp-validation-for="Voting.Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voting.Description" class="control-label">Описание</label>
                <textarea asp-for="Voting.Description" class="form-control"></textarea>
                <span asp-validation-for="Voting.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voting.StartDate" class="control-label">Дата начала</label>
                <input asp-for="Voting.StartDate" class="form-control" />
                <span asp-validation-for="Voting.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voting.EndDate" class="control-label">Дата окончания</label>
                <input asp-for="Voting.EndDate" class="form-control" />
                <span asp-validation-for="Voting.EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voting.OrganizationId" class="control-label">Организация</label>
                <select asp-for="Voting.OrganizationId" class="form-control" asp-items="ViewBag.OrganizationId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
                <a class="btn btn-light" asp-page="Index">Назад</a>
            </div>

        </div>
        <div class="col-md-6">
            <h5>Повестка дня</h5>
            <hr />
            <div id="fields"></div>

            <button id="btnAddField" class="btn btn-light">Добавить поле</button>

            <script type="text/javascript">

                var fields = document.querySelector('#fields');
                var addFieldButton = document.querySelector('#btnAddField');

                addFieldButton.addEventListener("click", function (e) {
                    e.preventDefault();
                    var input = document.createElement("input");
                    input.classList.add('form-control');
                    input.classList.add('mb-3');
                    input.name = "Options";

                    fields.append(input);
                })
            </script>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OOOVote/OOOVote/Pages/Votings/Details.cshtml
@page
@model OOOVote.Pages.DetailsModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = Model.Voting.Subject;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex justify-content-between align-items-center mb-3">
    <div class="d-flex align-items-baseline">
        <a class="btn btn-light" asp-page="./Index">Назад</a>
        <h4 class="ml-3">@ViewData["Title"]</h4>
    </div>

    <div class="d-flex align-items-center">
        <a class="ml-2 btn btn-light" asp-page="./Edit" asp-route-id="@Model.Voting.Id">Редактировать</a>
    </div>
</div>

<div class="row mb-3">
    <div class="card col-6">
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-4">
                    Тема
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Voting.Subject)
                </dd>
                <dt class="col-sm-4">
                    Описание
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Voting.Description)
                </dd>
                <dt class="col-sm-4">
                    Начало
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Voting.StartDate)
                </dd>
                <dt class="col-sm-4">
                    Окончание
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Voting.EndDate)
                </dd>
                <dt class="col-sm-4">
                    Организация
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Voting.Organization.Name)
                </dd>
            </dl>
        </div>
    </div>
    <div class="card col-6">
        <div class="card-body">
            <h5 class="card-title">Ход голосования</h5>
            @if (DateTime.UtcNow > Model.Voting.EndDate)
            {
                <h3>Голосование завершено</h3>
            }
            else
            {
                <span>До окончания голосования:</span>
                <h3 id="timer"></h3>
                <script>
                var x = setInterval(function () {
                    var countDownDate = new Date(Date.parse("@Model.Voting.EndDate.ToString("o")"));
                    // Get today's date and time
                    var now = new Date().getTime();

                    // Find the distance between now and the count down date
                    var distance = countDownDate - now;

                    // Time calculations for days, hours, minutes and seconds
                    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                    var seconds = Math.floor((distance % (1000 * 60)) / 1000);

                    // Display the result in the element with id="demo"
                    document.getElementById("timer").innerHTML = days + "д " + hours + "ч "
                        + minutes + "м " + seconds + "с ";

                    // If the count down is finished, write some text
                    if (distance < 0) {
                        clearInterval(x);
                        document.getElementById("timer").innerHTML = "Голосование завершено";
                    }
                }, 1000);
                </script>
            }
            <hr />
            @if (!Model.ShowResults)
            {
                <h5 class="card-title">Повестка голосования</h5>
                <form method="post">
                    <div class="accordion" id="accordionExample">
                        @foreach (var item in Model.Voting.VotingOptions)
                        {
                            <div class="card">
                                <div class="card-header p-0" id="headingOne">
                                    <div class="mb-0">
                                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse_@item.Id" aria-expanded="true" aria-controls="collapseOne">
                                            @item.Title
                                        </button>
                                    </div>
                                </div>

                                <div id="collapse_@item.Id" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                                    <div class="card-body">
                                        <div class="form-check form-check-inline">
                                            <input asp-for="UserVotes[item.Id]" class="form-check-input" type="radio" value="0">
                                            <label class="form-check-label" for="inlineRadio1">За</label>
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <input asp-for="UserVotes[item.Id]" class="form-check-input" type="radio" value="1">
                                            <label class="form-check-label" for="inlineRadio2">Против</label>
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <input asp-for="UserVotes[item.Id]" class="form-check-input" type="radio" value="2" checked>
                                            <label class="form-check-label" for="inlineRadio3">Воздерживаюсь</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Проголосовать" class="btn btn-primary" />
                    </div>
                </form>
            }
            else
            {
                @foreach (var item in Model.VotingResults)
                {
                    <h6>@item.Key</h6>
                    <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: @(item.Value.AgreeCount*1.0/Model.UserCount*100)%">За - @(item.Value.AgreeCount)</div>
                        <div class="progress-bar bg-danger" role="progressbar" style="width: @(item.Value.DisagreeCount*1.0/Model.UserCount*100)%">Против - @(item.Value.DisagreeCount)</div>
                        <div class="progress-bar bg-secondary" role="progressbar" style="width: @(item.Value.NotVotedCount*1.0/Model.UserCount*100)%">Воздержались - @(item.Value.NotVotedCount)</div>
                    </div>
                    @if (Model.IsVotingEnded)
                    {
                        if (item.Value.AgreeCount * 1.0 / Model.UserCount * 100 > 51)
                        {
                            <span class="text-success">Принято решение - ЗА</span>
                        }
                        if (item.Value.DisagreeCount * 1.0 / Model.UserCount * 100 > 51)
                        {
                            <span class="text-danger">Принято решение - ПРОТИВ</span>
                        }
                        if (item.Value.AllVotedCount * 1.0 / Model.UserCount * 100 < 51 ||
                            item.Value.NotVotedCount * 1.0 / Model.UserCount * 100 > 51)
                        {
                            <span class="text-secondary">Нет кворума</span>
                        }
                    }
                }
                <br />
                <form method="post">
                    <button type="submit" asp-page-handler="DownloadFile" asp-route-id="@Model.Voting.Id"
                            class="btn btn-sm btn-secondary">
                        Cкачать протокол
                    </button>
                </form>
            }
        </div>
    </div>
</div>

<div class="row">
    <div class="card col-12">
        <div class="card-body">
            <h5 class="card-title">Чат голосования</h5>
            <div class="row">
                <div class="col-12">
                    <input type="hidden" id="groupInput" value="@Model.Voting.Id.ToString()" class="form-control" />
                    <div class="input-group my-2">
                        <input type="text" id="messageInput" class="form-control" placeholder="Введите сообщение" aria-label="Recipient's username" aria-describedby="button-addon2">
                        <div class="input-group-append">
                            <input type="button" class="btn btn-outline-secondary" value="Отправить" id="sendButton" />
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <div class="row" style="max-height:600px">
                <div class="col-12">
                    <dl id="messagesList">
                        @foreach (var item in Model.Voting.VotingMessages)
                        {
                            <dt>@string.Format("{0} {1}", item.User.LastName, item.User.FirstName)</dt>
                            <dd>@item.Message</dd>
                        }
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/lib/@@aspnet/signalr/dist/browser/signalr.min.js"></script>
<script src="~/js/chat.js"></script>